# Generated by Django 3.0.3 on 2020-02-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0002_playlist_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_href',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='playlists',
            field=models.ManyToManyField(to='radioFromRecentlyPlayedTracks.Playlist'),
        ),
    ]
