# Generated by Django 3.0.3 on 2020-03-02 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0003_auto_20200224_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='tracks',
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radioFromRecentlyPlayedTracks.User'),
        ),
        migrations.AddField(
            model_name='track',
            name='belongs_to_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='radioFromRecentlyPlayedTracks.Playlist'),
        ),
        migrations.AddField(
            model_name='track',
            name='trackID',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
