# Generated by Django 3.0.3 on 2020-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0004_auto_20200302_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='valence',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
