# Generated by Django 3.0.3 on 2020-03-02 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0005_auto_20200302_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='trackID',
        ),
        migrations.RemoveField(
            model_name='track',
            name='valence',
        ),
    ]
