# Generated by Django 3.0.3 on 2020-03-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0006_auto_20200302_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
