# Generated by Django 3.0.3 on 2020-03-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioFromRecentlyPlayedTracks', '0008_track_artistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='valence',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
