# Generated by Django 3.0.3 on 2020-03-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('playlist_href', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('artist', models.CharField(max_length=100, null=True)),
                ('artistID', models.CharField(max_length=100, null=True)),
                ('valence', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('belongs_to_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moodFlip.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moodFlip.User'),
        ),
    ]
