# Generated by Django 3.1.2 on 2020-10-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodFlip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='valence',
            new_name='mood',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='moodFlip.user'),
        ),
        migrations.AlterField(
            model_name='track',
            name='belongs_to_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='moodFlip.playlist'),
        ),
    ]
