# Generated by Django 3.1.2 on 2020-10-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodFlip', '0002_auto_20201021_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='belongs_to_playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='belongs_to_playlist',
            field=models.ManyToManyField(to='moodFlip.Playlist'),
        ),
    ]
