# Generated by Django 3.1.2 on 2020-12-13 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodFlip', '0003_auto_20201023_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='belongs_to_playlist',
        ),
        migrations.AddField(
            model_name='track',
            name='belongs_to_playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moodFlip.playlist'),
        ),
    ]
